<input type="hidden" name="week" value="<?=htmlentities($week)?>">
<input type="hidden" name="day" value="<?=htmlentities($plat['day'])?>">
<input type="hidden" name="statut" value="<?=htmlentities($statut)?>">
<input type="hidden" name="content" value="<?=htmlentities($content)?>">
<input type="hidden" name="price" value="<?=htmlentities($price)?>">
<button type="submit" class="btn btn-success pull-right" name="action" value="edit_plat"><?=htmlentities($btn)?></button>