<h2>Ajoute un commentaire</h2>
<form class="form-horizontal" action="" method="post">
  <input type="hidden" name="commandId" value="<?= $commandId ?>">
  <div class="form-group">
    <label for="content">Content</label>
    <textarea class="form-control" name="content" placeholder="Entrez le menu du jour"></textarea>
  </div>
  <button class="btn btn-success" type="submit" name="action" value="creat_comment">Envoyer</button>
</form>
